services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql  # This persists the database data
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: for initial SQL scripts
    ports:
      - "3306:3306"
    networks:
      - messaging_network

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: ${MYSQL_DB}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - messaging_network

volumes:
  mysql_data:  # Named volume declaration for persistent storage
    driver: local

networks:
  messaging_network:
    driver: bridge