pipeline {
    agent any
    
    tools {
        python "Python3"  // Name of your Python installation in Jenkins
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                credentialsId: 'your-github-credentials-id',
                url: 'https://github.com/alx-backend-python.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r messaging_app/requirements.txt'
            }
        }
        
        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh 'pytest --junitxml=test-results.xml'
                }
            }
            post {
                always {
                    junit 'messaging_app/test-results.xml'
                }
            }
        }
    }
    
    post {
        always {
            // Optional: Clean up workspace
            cleanWs()
        }
    }
}